apiVersion: v1
kind: Pod
metadata:
  name: puff-pod
  labels:
    run: puff-pod
    service: puff-pod
spec:
  containers:
    - image: nginx
      name: puff-nginx
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: puff-nginx-emptydir
      ports:
        - containerPort: 80
      resources:
        limits:
          cpu: "0.3"
          memory: "256Mi"
        requests:
          cpu: "0.1"
          memory: "128Mi"
      command: ["sh", "-c"]
      args:
        - echo "DEU CERTO" > /usr/share/nginx/html/index.html \
          && echo "<h1>Welcome to Puff Nginx Server</h1>" >> /usr/share/nginx/html/index.html \
          && nginx -g 'daemon off;'
    - image: alpine
      name: puff-alpine
      args:
        - sleep
        - "3600"
      resources:
        limits:
          cpu: "0.2"
          memory: "128Mi"
        requests:
          cpu: "0.05"
          memory: "64Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: puff-nginx-emptydir
      emptyDir:
        sizeLimit: "512Mi"
status: {}
